/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import {ToastContainer} from 'react-toastify'
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const kufiArabic = Noto_Kufi_Arabic({ subsets: ["arabic"], weight: ["500"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello kemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ToastContainer theme="colored" position="top-center"/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
